plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'expo.modules.shipsync'
version = '1.0.0'
android {
  namespace "expo.modules.shipsync"
  defaultConfig { consumerProguardFiles("proguard-rules.pro") }
}
dependencies {
  implementation 'androidx.work:work-runtime-ktx:2.9.1'
}
